version: '1.0'

networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 00.00.00.00/16       //Remplacer par de fausses adresses IP pour des raisons de sécurité
          gateway: 00.00.0.1           //Remplacer par de fausses adresses IP pour des raisons de sécurité

services:
  db:
    build: ./db
    image: ghcr.io/ikeepmyideas/db
    restart: always
    environment:
      MYSQL_DATABASE: au_temps_donne
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - my_app_network
    volumes:
      - ./db_storage:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    depends_on:
      - db
    image: ghcr.io/ikeepmyideas/backend
    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: au_temps_donne
    networks:
      - my_app_network
    ports:
      - "8000:8000"
    restart: always

  frontend:
    depends_on:
      - backend
    image: ghcr.io/ikeepmyideas/frontend
    networks:
      - my_app_network
    ports:
      - "3000:3000"
