version: '3'

services:
  db:
    image: ghcr.io/ikeepmyideas/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ghcr.io/ikeepmyideas/backend
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  frontend:
    image: ghcr.io/ikeepmyideas/frontend 
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data:
